services:
  app:
    image: docker-compose-app:dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    command: make dev

  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
