FROM node:20.12.2

WORKDIR /app

# Important for layer caching
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

# Create .env from .env.example for hexlet-check
RUN cp -n .env.example .env || true

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
