name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          # Start with defaults
          cp .env.defaults .env
          # Override with secrets if they exist
          [ -n "${{ secrets.DATABASE_HOST }}" ] && echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env || true
          [ -n "${{ secrets.DATABASE_NAME }}" ] && echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env || true
          [ -n "${{ secrets.DATABASE_USERNAME }}" ] && echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env || true
          [ -n "${{ secrets.DATABASE_PASSWORD }}" ] && echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env || true
          [ -n "${{ secrets.DATABASE_PORT }}" ] && echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env || true

      - name: Run tests
        run: make ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: sazanik/docker-compose-app:latest
